### ISSUE TITLE
Please provide insight on markdown to tufte.

### ISSUE THREAD

**Issue by malisetti** [mandaris/TuftePelican#1]
I was trying to port this to hugo theme. https://github.com/mseshachalam/tufteTheme 
and came to know about this issue https://github.com/edwardtufte/tufte-css/issues/21 

The structure of the html is different from the markdown converted.

**Comment by mandaris** [comment]
Hello Malisetti! Are you still having an issue with this. To be honest, I'd have to re-learn how this works. I believe that I had a markdown plugin that I made to resolve this. If you want it, I can add it as a gist.

**Comment by malisetti** [comment]
No problem.

**Comment by mandaris** [comment]
You closed the issue, but here is the gist if you are still interested.

It's to be added to the liquid tags plugin.

[gist](https://gist.github.com/mandaris/78a88d7cd2d1ecded07a0b0680a45731)
